name: Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./make/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: nexent/nexent-base:latest

      - name: Build main application image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./make/main/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: nexent/nexent:latest

      - name: Build data process image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./make/data_process/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: nexent/nexent-data-process:latest

      - name: Build web frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./make/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: nexent/nexent-web:latest 